services:
  web:
    build: .
    command: >
      bash -c "python /app/manage.py migrate
      && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - djangonetwork
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - djangonetwork
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  djangonetwork:
    driver: bridge
