# Generated by Django 5.1.4 on 2025-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='estimated_time',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
